archivers/7-zip: fix build on big-endian
Checking for _LITTLE_ENDIAN causes:
../../Archive/../Compress/../../../C/CpuArch.h:280:4: error: Stop_Compiling_Bad_Endian
  280 |   #error Stop_Compiling_Bad_Endian
      |    ^

This is because sys/_endian.h defines _LITTLE_ENDIAN.