databases/fastdb: fix build
This port does some strange stuff, like undefining BYTE_ORDER macro,
because of which it fails to build:
In file included from src/unisock.cpp:28:
/usr/include/netinet/tcp.h: In function 'uint16_t __tcp_get_flags(const tcphdr*)':
/usr/include/netinet/tcp.h:85:32: error: 'const struct tcphdr' has no member named 'th_x2'
   85 |         return (((uint16_t)th->th_x2 << 8) | th->th_flags);
      |                                ^~~~~
/usr/include/netinet/tcp.h: In function 'void __tcp_set_flags(tcphdr*, uint16_t)':
/usr/include/netinet/tcp.h:91:13: error: 'struct tcphdr' has no member named 'th_x2'
   91 |         th->th_x2 = (flags >> 8) & 0x0f;
      |             ^~~~~