textproc/regex2dfa: broken everywhere, very much out of date
/bin/sh ../../libtool --tag=CXX   --mode=compile c++ -DHAVE_CONFIG_H   -I./../include    -O2 -pipe -fstack-protector-strong -fno-strict-aliasing    -std=c++0x -MT fst.lo -MD -MP -MF .deps/fst.Tpo -c -o fst.lo fst.cc
libtool: compile:  c++ -DHAVE_CONFIG_H -I./../include -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -std=c++0x -MT fst.lo -MD -MP -MF .deps/fst.Tpo -c fst.cc -o fst.o
In file included from fst.cc:26:
In file included from ./../include/fst/matcher-fst.h:26:
In file included from ./../include/fst/lookahead-matcher.h:28:
In file included from ./../include/fst/label-reachable.h:32:
In file included from ./../include/fst/accumulator.h:36:
In file included from ./../include/fst/replace.h:40:
In file included from ./../include/fst/state-table.h:31:
./../include/fst/bi-table.h:356:31: error: no member named 's_' in 'VectorHashBiTable<I, T, S, FP, H, HS>'
  356 |       : selector_(new S(table.s_)),
      |                         ~~~~~ ^
1 error generated.

Upstream has since rewritten the whole thing in Python.
Perhaps an update is in order.

Approved by:	portmgr (build fix blanket)