net/samba422: Add a missing dependency: ncurses
This should address the following errors:

    Error: /usr/local/bin/samba-regedit is linked to /usr/local/lib/libform.so.6 from devel/ncurses but it is not declared as a dependency
    Warning: you need USES+=ncurses
    Error: /usr/local/bin/samba-regedit is linked to /usr/local/lib/libncurses.so.6 from devel/ncurses but it is not declared as a dependency
    Warning: you need USES+=ncurses
    Error: /usr/local/bin/samba-regedit is linked to /usr/local/lib/libtinfo.so.6 from devel/ncurses but it is not declared as a dependency
    Warning: you need USES+=ncurses
    Error: /usr/local/bin/samba-regedit is linked to /usr/local/lib/libpanel.so.6 from devel/ncurses but it is not declared as a dependency
    Warning: you need USES+=ncurses