databases/mongodb70: 7.0.35
Release notes:
https://www.mongodb.com/docs/manual/release-notes/7.0/#7.0.35---june-9--2026

- gen-config.sh is move to scripts/gen-config.sh
- Patch added to circumvent these errors:
src/mongo/util/net/openssl_init.cpp:247:51: error: no member named 'opensslPrimaryDRBGReseedMaxRequests' in namespace 'mongo::crypto'
src/mongo/util/net/openssl_init.cpp:249:45: error: no member named 'opensslPrimaryDRBGReseedMaxTime' in namespace 'mongo::crypto'
- disabled PATCH_FILE for python3.12, didn't apply
- other patches just got a refresh

Security:	CVE-2026-9740
Security:	CVE-2026-9741
Security:	CVE-2026-9746
Security:	CVE-2026-9747
Security:	CVE-2026-9748
Security:	CVE-2026-9749
Security:	CVE-2026-9750
Security:	CVE-2026-9751
Security:	CVE-2026-9752
Security:	CVE-2026-9753