x11/libxfce4windowing: Fix QA and plist issue
====> Running Q/A tests (stage-qa)
Error: .la libraries found, port needs USES=libtool
*** Error code 1

===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned:
share/gtk-doc/html/libxfce4windowing/XfwApplication.html
Error: Orphaned: share/gtk-doc/html/libxfce4windowing/XfwMonitor.html
Error: Orphaned: share/gtk-doc/html/libxfce4windowing/XfwScreen.html
(snip)

Approved by:	blanket