emulators/virtualbox-ose{,-legacy}: Limit python to 3.10-3.11
This is temporary workaround for build error:

/usr/ports/emulators/virtualbox-ose/work/VirtualBox-6.1.50/src/libs/xpcom18a4/python/src/VariantUtils.cpp:197:7: error: use of undeclared identifier 'PyUnicode_GET_SIZE'; did you mean 'PyDict_GET_SIZE'?
                if (PyUnicode_GET_SIZE(val_use) == 0) {
                    ^~~~~~~~~~~~~~~~~~
                    PyDict_GET_SIZE
/usr/local/include/python3.12/cpython/dictobject.h:53:26: note: 'PyDict_GET_SIZE' declared here
static inline Py_ssize_t PyDict_GET_SIZE(PyObject *op) {
                         ^
/usr/ports/emulators/virtualbox-ose/work/VirtualBox-6.1.50/src/libs/xpcom18a4/python/src/VariantUtils.cpp:501:38: error: use of undeclared identifier 'PyUnicode_AS_UNICODE'
                                FILL_SIMPLE_POINTER( PRUnichar, *PyUnicode_AS_UNICODE(val_use) );
                                                                 ^
/usr/ports/emulators/virtualbox-ose/work/VirtualBox-6.1.50/src/libs/xpcom18a4/python/src/VariantUtils.cpp:829:8: error: use of undeclared identifier 'PyUnicode_GetSize'
                        if (PyUnicode_GetSize(ob) == 0) {
                            ^

Support for the python 3.12+ was added in the VirtualBox 7.0.
Maybe I'll partially port this in older VirtualBox ports later.

PR:	292189 285957