www/webkit2-gtk: fix build with clang >= 20
With clang 20 or higher webkit2-gtk fails to build, with errors similar
to:

    /wrkdirs/usr/ports/www/webkit2-gtk/work-40/.build/WTF/Headers/wtf/EnumTraits.h:246:20: error: no matching function for call to 'enumName'
      246 |         names[i] = enumName<static_cast<E>(static_cast<unsigned>(i))>();
          |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /wrkdirs/usr/ports/www/webkit2-gtk/work-40/.build/WTF/Headers/wtf/EnumTraits.h:233:9: note: in instantiation of function template specialization 'WTF::enumNames()::(anonymous class)::operator()<std::integral_constant<unsigned long, 64>>' requested here
      233 |         func(std::integral_constant<size_t, i>());
          |         ^
    /wrkdirs/usr/ports/www/webkit2-gtk/work-40/.build/WTF/Headers/wtf/EnumTraits.h:234:9: note: in instantiation of function template specialization 'WTF::detail::forConstexpr<64UL, 256UL, (lambda at /wrkdirs/usr/ports/www/webkit2-gtk/work-40/.build/WTF/Headers/wtf/EnumTraits.h:245:36)>' requested here
      234 |         forConstexpr<i + 1, end>(func);
          |         ^
    ...

This is fixed by https://commits.webkit.org/292321@main for
https://bugs.webkit.org/show_bug.cgi?id=289669, so import that patch,
plus https://commits.webkit.org/290345@main, which is a prerequisite.

PR:		292165
Approved by:	vishwin (maintainer)
MFH:		2025Q4