games/blues: fix build on powerpc64*
Since 15.0-RELEASE, objcopy --localize-hidden seems to
have stopped working properly on powerpc64*.
That causes linking issues:
ld: error: duplicate symbol: play_music
>>> defined at sound.c:78 (bb/sound.c:78)
>>>            game_bb.o:(play_music)
>>> defined at sound.c:66 (p2/sound.c:66)
>>>            game_p2.o:(.text+0x16900)

Everything seems fine on 14.3-RELEASE.