databases/closql*: Mark MAKE_JOBS_UNSAFE
It seems parallel build may fail as following.

Compiling closql.el
 Creating closql-autoloads.el
 Checking function declarations
Opening input file: No such file or directory, /wrkdirs/usr/ports/databases/closql/work-full/closql-2.2.0/.#closql-autoloads.el

Error: file-missing ("Opening input file" "No such file or directory" "/wrkdirs/usr/ports/databases/closql/work-full/closql-2.2.0/.#closql-autoloads.el")
  mapbacktrace(#f(compiled-function (evald func args flags) #<bytecode 0x1f53201d3faed07c>))
  debug-early-backtrace()
  debug-early(error (file-missing "Opening input file" "No such file or directory" "/wrkdirs/usr/ports/databases/closql/work-full/closql-2.2.0/.#closql-autoloads.el"))
  insert-file-contents("./.#closql-autoloads.el")
  check-declare-scan("./.#closql-autoloads.el")
  check-declare-files("./.#closql-autoloads.el" "./closql-autoloads.el" "./closql.el")
  apply(check-declare-files ("./.#closql-autoloads.el" "./closql-autoloads.el" "./closql.el"))
  check-declare-directory("~/closql-2.2.0/")
  eval((check-declare-directory default-directory) t)
  command-line-1(("-L" "/usr/local/share/emacs/29.4/site-lisp/compat" "-L" "/usr/local/share/emacs/29.4/site-lisp/emacsql" "-L" "." "--eval" "(check-declare-directory default-directory)"))
  command-line()
  normal-top-level()
gmake: *** [Makefile:38: check-declare] Error 255
gmake: *** Waiting for unfinished jobs....
===> Compilation failed unexpectedly.
Try to set MAKE_JOBS_UNSAFE=yes and rebuild before reporting the failure to
the maintainer.
*** Error code 1

Stop.

Reported by:	pkg-fallout