multimedia/mkvtoolnix: fix build with libc++ 21
With libc++ 21 multimedia/mkvtoolnix fails to build, with errors similar
to:

    In file included from lib/fmt/src/os.cc:13:
    In file included from lib/fmt/include/fmt/os.h:11:
    lib/fmt/include/fmt/format.h:745:28: fatal error: use of undeclared identifier 'malloc'
      745 |     T* p = static_cast<T*>(malloc(n * sizeof(T)));
          |                            ^~~~~~

This is because malloc and free are defined in <cstdlib>, and os.h does
not explicitly include it. (Before libc++ 21, the fmt library was
"lucky" that <cstdlib> was included transitively, but this is no longer
the case.)

PR:		293182
Approved by:	riggs (maintainer)
MFH:		2026Q1