comms/morse: update 2.5 => 2.6
* Switch to Gitlab upstream
* Use textproc/xmlto for man page generation
* Format using portfmt(1)
* Actualise patches to current version
* Use explicit localbase:ldflags helper for X11 option instead of CFLAGS and LDFLAGS
* Regression: build with X11 option set failed with:
  ./alarm.h:15:15: error: a parameter list without types is only allowed in a function definition

PR:		288513
Approved by:	yuri@ (Mentor)