security/py-cryptography: Fix stage QA errors with py-maturin 1.12.0+
* If built with py-maturin 1.12.0+ following stage QA errors are emitted:

[...]
====> Running Q/A tests (stage-qa)
Error: Python package installs top-level 'docs/' directory in site-packages
Error:   Location: lib/python3.11/site-packages/docs
[...]
Error: Python package installs top-level 'tests/' directory in site-packages
Error:   Location: lib/python3.11/site-packages/tests
[...]

* This is because older versions of py-maturin didn't install these
  stray files due to an bug with the "include" pattern in
  "pyproject.toml".  With version 1.12.0, these files are now installed.

Approved by:	portmgr (build fix blanket)

security/py-cryptography: Convert to PATCH_SITES