emulators/virtualbox-ose*: Fix vboxvfs build on 16-CURRENT
/wrkdirs/usr/ports/emulators/virtualbox-ose-additions/work/VirtualBox-6.1.50/src/VBox/Additions/freebsd/vboxvfs/vboxvfs_vnops.c:1271:9: error: use of undeclared identifier 'NULLVP'
 1271 |         *vpp = NULLVP;
      |                ^
/wrkdirs/usr/ports/emulators/virtualbox-ose-additions/work/VirtualBox-6.1.50/src/VBox/Additions/freebsd/vboxvfs/vboxvfs_vnops.c:1281:3: error: call to undeclared function 'VREF'; ISO C99 and later do not support implicit function declarations [-Werror,-Wimplicit-function-declaration]
 1281 |                 VREF(dvp);
      |                 ^

Commits that broke the build:
https://cgit.freebsd.org/src/commit/sys/sys/vnode.h?id=7e4c451c12aeb26cc1179221b8230c491b17cf00
https://cgit.freebsd.org/src/commit/sys/sys/vnode.h?id=01c8e2e33df81b242d73a23de49a6b61f33c24c1

PR:		289992
Reported by:	pkg-fallout
MFH:		2025Q4