devel/py-libevdev: add missing dependency
>>> import libevdev
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/libevdev/__init__.py", line 23, in <module>
    from .device import Device, InputAbsInfo
  File "/usr/local/lib/python3.11/site-packages/libevdev/device.py", line 29, in <module>
    from .event import InputEvent
  File "/usr/local/lib/python3.11/site-packages/libevdev/event.py", line 23, in <module>
    from .const import EventType, EventCode
  File "/usr/local/lib/python3.11/site-packages/libevdev/const.py", line 427, in <module>
    _load_consts()
  File "/usr/local/lib/python3.11/site-packages/libevdev/const.py", line 352, in _load_consts
    Libevdev()  # classmethods, need to make sure it's loaded at once
    ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/libevdev/_clib.py", line 395, in __init__
    super(Libevdev, self).__init__()
  File "/usr/local/lib/python3.11/site-packages/libevdev/_clib.py", line 76, in __init__
    self._load()
  File "/usr/local/lib/python3.11/site-packages/libevdev/_clib.py", line 83, in _load
    cls._lib = cls._cdll()
               ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/libevdev/_clib.py", line 123, in _cdll
    return ctypes.CDLL("libevdev.so.2", use_errno=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: Shared object "libevdev.so.2" not found, required by "python3.11"

Reported by:	vishwin