security/wazuh-manager: Fix error when running with legacy algorithms
Traceback (most recent call last):
  File "/var/ossec/framework/scripts/cluster_control.py", line 16, in <module>
    import wazuh.core.cluster.cluster
  File "/var/ossec/framework/python/lib/python3.11/site-packages/wazuh/core/cluster/cluster.py", line 22, in <module>
    from wazuh.core.cluster.utils import (
  File "/var/ossec/framework/python/lib/python3.11/site-packages/wazuh/core/cluster/utils.py", line 21, in <module>
    from wazuh.core.configuration import get_ossec_conf
  File "/var/ossec/framework/python/lib/python3.11/site-packages/wazuh/core/configuration.py", line 23, in <module>
    from wazuh.core.utils import cut_array, load_wazuh_xml, safe_move
  File "/var/ossec/framework/python/lib/python3.11/site-packages/wazuh/core/utils.py", line 32, in <module>
    from api import configuration
  File "/var/ossec/framework/python/lib/python3.11/site-packages/api/configuration.py", line 13, in <module>
    from cryptography import x509
  File "/var/ossec/framework/python/lib/python3.11/site-packages/cryptography/x509/__init__.py", line 7, in <module>
    from cryptography.x509 import certificate_transparency, verification
  File "/var/ossec/framework/python/lib/python3.11/site-packages/cryptography/x509/certificate_transparency.py", line 8, in <module>
    from cryptography.hazmat.bindings._rust import x509 as rust_x509
RuntimeError: OpenSSL 3.0's legacy provider failed to load. This is a fatal error by default, but cryptography supports running without legacy algorithms by setting the environment variable CRYPTOGRAPHY_OPENSSL_NO_LEGACY. If you did not expect this error, you have likely made a mistake with your OpenSSL configuration.

Approved by:    acm@