java/openjdk17: fix build without MAKE_JOBS_UNSAFE
Put back _MAKE_JOBS with a description why it is set empty.

Fixes:
===>  Building for openjdk17-17.0.16+8.1_2
Error: 'make -jN' is not supported, use 'make JOBS=N'

NB: this error came from work/jdk17u-jdk-17.0.16-8-1/make/InitSupport.gmk:119

Bump portrevision so future failures are easy to trace back to specific
port version.

Reported-by: https://lists.freebsd.org/archives/freebsd-ports/2025-September/008453.html