x11/quickshell: Unbreak build
The port recently started failing to build with the following error:

FAILED: [code=1] src/services/pipewire/CMakeFiles/quickshell-service-pipewire.dir/quickshell-service-pipewire_autogen/mocs_compilation.cpp.o
/usr/local/libexec/ccache/c++ -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_QMLINTEGRATION_LIB -DQT_QML_LIB -DQT_QUICK_LIB -D_REENTRANT -I/wrkdirs/usr/ports/x11/quickshell/work/.build/src/services/pipewire/quickshell-service-pipewire_autogen/include -I/wrkdirs/usr/ports/x11/quickshell/work/quickshell/src/services/pipewire -isystem /usr/local/include/qt6/QtQml -isystem /usr/local/include/qt6 -isystem /usr/local/include/qt6/QtCore -isystem /usr/local/lib/qt6/mkspecs/freebsd-clang -isystem /usr/local/include/qt6/QtQmlIntegration -isystem /usr/local/include/qt6/QtNetwork -isystem /usr/local/include/pipewire-0.3 -isystem /usr/local/include/spa-0.2 -isystem /usr/local/include/qt6/QtQuick -isystem /usr/local/include/qt6/QtGui -isystem /usr/local/include/qt6/QtOpenGL -O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing   -isystem /usr/local/include -O2 -g -DNDEBUG -std=gnu++20 -Wall -Wextra -Wno-vla-cxx-extension -pthread -D_REENTRANT -fno-strict-aliasing -fno-strict-overflow -Winvalid-pch -Xclang -include-pch -Xclang /wrkdirs/usr/ports/x11/quickshell/work/.build/CMakeFiles/qs-pchset-common.dir/cmake_pch.hxx.pch -Xclang -include -Xclang /wrkdirs/usr/ports/x11/quickshell/work/.build/CMakeFiles/qs-pchset-common.dir/cmake_pch.hxx -MD -MT src/services/pipewire/CMakeFiles/quickshell-service-pipewire.dir/quickshell-service-pipewire_autogen/mocs_compilation.cpp.o -MF src/services/pipewire/CMakeFiles/quickshell-service-pipewire.dir/quickshell-service-pipewire_autogen/mocs_compilation.cpp.o.d -o src/services/pipewire/CMakeFiles/quickshell-service-pipewire.dir/quickshell-service-pipewire_autogen/mocs_compilation.cpp.o -c /wrkdirs/usr/ports/x11/quickshell/work/.build/src/services/pipewire/quickshell-service-pipewire_autogen/mocs_compilation.cpp
error: signed integer overflow handling differs in PCH file vs. current file

Though I'm not (yet) sure what is causing that, setting NO_PCH to ON
with cmake appears to work around the issue.