audio/rubberband: fix build with libc++ 21
With libc++ 21 audio/rubberband fails to build, with errors similar to:

    In file included from ../src/common/mathmisc.cpp:24:
    ../src/common/mathmisc.h:58:1: error: unknown type name 'size_t'; did you mean 'std::size_t'?
       58 | size_t roundUp(size_t value); // to nearest power of two
          | ^~~~~~
          | std::size_t
    /usr/include/c++/v1/__cstddef/size_t.h:20:7: note: 'std::size_t' declared here
       20 | using size_t = decltype(sizeof(int));
          |       ^

This is because mathmisc.h depended on <stddef.h> being transitively
included, which is no longer the case. Add #include <stddef.h> to fix
the problem.

PR:		292868
Approved by:	acm (maintainer)
MFH:		2026Q1