www/py-werkzeug2: Fix PLIST
- Convert to USE_PYTHON=autoplist
- Bump PORTREVISION for package change

====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug-2.3.8.dist-info/METADATA
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug-2.3.8.dist-info/RECORD
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug-2.3.8.dist-info/WHEEL
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug-2.3.8.dist-info/licenses/LICENSE.rst
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/__pycache__/__init__%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/__pycache__/__init__%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/__pycache__/_internal%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/__pycache__/_internal%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/__pycache__/_reloader%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/__pycache__/_reloader%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/__pycache__/exceptions%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/__pycache__/exceptions%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/__pycache__/formparser%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/__pycache__/formparser%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/__pycache__/http%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/__pycache__/http%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/__pycache__/local%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/__pycache__/local%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/__pycache__/security%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/__pycache__/security%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/__pycache__/serving%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/__pycache__/serving%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/__pycache__/test%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/__pycache__/test%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/__pycache__/testapp%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/__pycache__/testapp%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/__pycache__/urls%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/__pycache__/urls%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/__pycache__/user_agent%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/__pycache__/user_agent%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/__pycache__/utils%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/__pycache__/utils%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/__pycache__/wsgi%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/__pycache__/wsgi%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/datastructures/__pycache__/__init__%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/datastructures/__pycache__/__init__%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/datastructures/__pycache__/accept%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/datastructures/__pycache__/accept%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/datastructures/__pycache__/auth%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/datastructures/__pycache__/auth%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/datastructures/__pycache__/cache_control%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/datastructures/__pycache__/cache_control%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/datastructures/__pycache__/csp%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/datastructures/__pycache__/csp%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/datastructures/__pycache__/etag%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/datastructures/__pycache__/etag%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/datastructures/__pycache__/file_storage%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/datastructures/__pycache__/file_storage%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/datastructures/__pycache__/headers%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/datastructures/__pycache__/headers%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/datastructures/__pycache__/mixins%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/datastructures/__pycache__/mixins%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/datastructures/__pycache__/range%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/datastructures/__pycache__/range%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/datastructures/__pycache__/structures%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/datastructures/__pycache__/structures%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/debug/__pycache__/__init__%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/debug/__pycache__/__init__%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/debug/__pycache__/console%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/debug/__pycache__/console%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/debug/__pycache__/repr%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/debug/__pycache__/repr%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/debug/__pycache__/tbtools%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/debug/__pycache__/tbtools%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/middleware/__pycache__/__init__%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/middleware/__pycache__/__init__%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/middleware/__pycache__/dispatcher%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/middleware/__pycache__/dispatcher%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/middleware/__pycache__/http_proxy%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/middleware/__pycache__/http_proxy%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/middleware/__pycache__/lint%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/middleware/__pycache__/lint%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/middleware/__pycache__/profiler%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/middleware/__pycache__/profiler%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/middleware/__pycache__/proxy_fix%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/middleware/__pycache__/proxy_fix%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/middleware/__pycache__/shared_data%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/middleware/__pycache__/shared_data%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/routing/__pycache__/__init__%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/routing/__pycache__/__init__%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/routing/__pycache__/converters%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/routing/__pycache__/converters%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/routing/__pycache__/exceptions%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/routing/__pycache__/exceptions%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/routing/__pycache__/map%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/routing/__pycache__/map%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/routing/__pycache__/matcher%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/routing/__pycache__/matcher%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/routing/__pycache__/rules%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/routing/__pycache__/rules%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/sansio/__pycache__/__init__%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/sansio/__pycache__/__init__%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/sansio/__pycache__/http%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/sansio/__pycache__/http%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/sansio/__pycache__/multipart%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/sansio/__pycache__/multipart%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/sansio/__pycache__/request%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/sansio/__pycache__/request%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/sansio/__pycache__/response%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/sansio/__pycache__/response%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/sansio/__pycache__/utils%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/sansio/__pycache__/utils%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/wrappers/__pycache__/__init__%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/wrappers/__pycache__/__init__%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/wrappers/__pycache__/request%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/wrappers/__pycache__/request%%PYTHON_EXT_SUFFIX%%.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/wrappers/__pycache__/response%%PYTHON_EXT_SUFFIX%%.opt-1.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/werkzeug/wrappers/__pycache__/response%%PYTHON_EXT_SUFFIX%%.pyc
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1

Approved by:	portmgr (blanket)
With hat:	python