net/rustconn: Update to 0.19.7
- Update list of lib dependencies
- Add a couple of patches (provided upstream) to fix cpal crate, that fails
  with error:

error[E0425]: cannot find value `ESTRPIPE` in crate `libc`
    --> /usr/local/poudriere/ports/default/net/rustconn/work/RustConn-0.19.5/cargo-crates/cpal-0.18.1/src/host/alsa/mod.rs:1125:42
     |
1125 |         Err(err) if err.errno() == libc::ESTRPIPE => return try_resume(&stream.handle),
     |                                          ^^^^^^^^
     |
    ::: /usr/local/poudriere/ports/default/net/rustconn/work/RustConn-0.19.5/cargo-crates/libc-0.2.189/src/unix/bsd/freebsdlike/mod.rs:630:1
     |
 630 | pub const ESPIPE: c_int = 29;
     | ----------------------- similarly named constant `ESPIPE` defined here
     |
help: a constant with a similar name exists
     |
1125 -         Err(err) if err.errno() == libc::ESTRPIPE => return try_resume(&stream.handle),
1125 +         Err(err) if err.errno() == libc::ESPIPE => return try_resume(&stream.handle),
     |

ChangeLog:	https://github.com/totoshko88/RustConn/releases/tag/v0.19.7
Reported by:	"github-actions[bot]" <notifications@github.com>