sysutils/yazi: Update to 26.1.22
- Add a patch (files/patch-yazi-fs_src_provider_local_casefold.rs) to fix
  the compilation which would otherwise fail with the following error:

error[E0432]: unresolved imports `libc::F_GETPATH`, `libc::O_SYMLINK`
   --> yazi-fs/src/provider/local/casefold.rs:164:13
    |
164 |     use libc::{F_GETPATH, O_RDONLY, O_SYMLINK, PATH_MAX};
    |                ^^^^^^^^^            ^^^^^^^^^ no `O_SYMLINK` in the root
    |                |
    |                no `F_GETPATH` in the root

ChangeLog:	https://github.com/sxyazi/yazi/blob/main/CHANGELOG.md#v26122
Reported by:	"github-actions[bot]" <notifications@github.com>