net/py-httpstat: Fix build with Python 3.14
Fix the error: AttributeError: 'Constant' object has no attribute 's'

Maintainer back to ports@ as current maintainer no longer uses this.

PR:		295020