science/InsightToolkit501: Mark BROKEN and set deprecation to 2026-04-30
Legacy version that is unsupported upstream and fails to build
error: no template named 'binary_function' in namespace 'std'

Reported by:	pkg-fallout