graphics/rawtherapee: pin GCC version to 13.
Apparently GCC 14 has new libstdc++ bits spill over somewhere,
and this would break rawtherapee's build at link time,
salvadore@ wrote

/usr/local/bin/ld: /tmp/ccgto6pJ.ltrans65.ltrans.o: in function `Spot::~Spot() [clone .cold]':
<artificial>:(.text.unlikely+0x89d): undefined reference to `__cxa_call_terminate'
/usr/local/bin/ld: /tmp/ccgto6pJ.ltrans76.ltrans.o: in function `(anonymous namespace)::dfInfo::updateBadPixelList(rtengine::RawImage const*) [clone ._omp_fn.0] [clone .cold]':
<artificial>:(.text.unlikely+0x93): undefined reference to `__cxa_call_terminate'
/usr/local/bin/ld: /tmp/ccgto6pJ.ltrans77.ltrans.o: in function `rtengine::ImProcFunctions::RGB_denoise(int, rtengine::Imagefloat*, rtengine::Imagefloat*, rtengine::Imagefloat*, float*, float*, float*, bool, rtengine::procparams::DirPyrDenoiseParams const&, double, rtengine::NoiseCurve const&, rtengine::NoiseCurve const&, float&, float&) [clone ._omp_fn.2] [clone .cold]':
<artificial>:(.text.unlikely+0x1d9): undefined reference to `__cxa_call_terminate'
/usr/local/bin/ld: /tmp/ccgto6pJ.ltrans81.ltrans.o: in function `rtengine::init(rtengine::Settings const*, Glib::ustring const&, Glib::ustring const&, bool) [clone ._omp_fn.0] [clone .lto_priv.0] [clone .cold]':
<artificial>:(.text.unlikely+0x4be): undefined reference to `__cxa_call_terminate'
/usr/local/bin/ld: /tmp/ccgto6pJ.ltrans84.ltrans.o: in function `rtengine::ImProcFunctions::ciecamloc_02float(rtengine::local_params&, int, rtengine::LabImage*, int, int, int, int, LUT<float> const&, bool, LUT<float> const&, bool, LUT<float> const&, bool, LUT<float> const&, bool, LUT<float> const&, bool, rtengine::LocCHCurve const&, rtengine::LocHHCurve const&, rtengine::LocLHCurve const&, bool, bool, bool, rtengine::LocwavCurve const&, bool, float&, float&, float&) [clone ._omp_fn.11] [clone .lto_priv.0] [clone .cold]':
<artificial>:(.text.unlikely+0x5f): undefined reference to `__cxa_call_terminate'

And this seems to be https://gcc.gnu.org/pipermail/libstdc++/2023-May/056011.html
related to C++ standards compliance - however __cxa_call_terminate
specifically is a libstdc++ export function, unavailable in libc++.

Rawtherapee needs to link against libc++ because otherwise all
C++ libraries it imports would also have to be compiled against
libstdc++.

Reported by:	Lorenzo salvadore@
PR:		284487