games/veloren-weekly: downgrade to s20250820 due to broken build/runtime
=> Fetched file size mismatch (expected 333168474, actual 339991225)

$ file veloren-v0.17.0-1004-g311bca4359*/assets/voxygen/audio/soundtrack/combat/clash/clash-start.ogg
veloren-v0.17.0-1004-g311bca4359.orig/assets/voxygen/audio/soundtrack/combat/clash/clash-start.ogg:   ASCII text
veloren-v0.17.0-1004-g311bca4359/assets/voxygen/audio/soundtrack/combat/clash/clash-start.ogg: Ogg data, Vorbis audio, stereo, 44100 Hz, ~499821 bps, created by: Xiph.Org libVorbis I

$ veloren-voxygen
[...]
PanicHookInfo: panicked at veloren-v0.17.0-1004-g311bca435996/cargo-crates/wgpu-26.0.1/src/api/instance.rs:115:13:
No wgpu backend feature that is implemented for the target platform was enabled. See `wgpu::Instance::enabled_backend_features()` for more information.

This reverts commit 8c1f5dd1f73a603eb4f3176346d2fff7e4425572.

Reported by:	pkg-fallout