devel/ispc: fix build with libc++ >= 20
With libc++ 20 or higher devel/ispc fails to build, with errors similar
to:

    /wrkdirs/usr/ports/devel/ispc/work/ispc-1.30.0/src/util.cpp:51:11: error: '__libcpp_verbose_abort' is missing exception specification 'noexcept'
       51 | void std::__libcpp_verbose_abort(char const *format, ...)
          |           ^
          |                                                           noexcept
    /usr/include/c++/v1/__verbose_abort:24:28: note: previous declaration is here
       24 |     __printf__, 1, 2) void __libcpp_verbose_abort(const char* __format, ...) _NOEXCEPT;
          |                            ^

This is because ispc attemps to override __libcpp_verbose_abort(), which
is an internal libc++ function, but it misses a noexcept specification.

However, overriding __libcpp_verbose_abort() is only necessary on older
versions of macOS. Therefore, exclude the whole #if block if the
operating system is not macOS.

PR:		293163
Approved by:	yuri (maintainer)
MFH:		2026Q1