misc/onnxruntime: fix build on powerpc64
VSX is required:
/wrkdirs/usr/ports/misc/onnxruntime/work/onnxruntime-1.23.2/onnxruntime/core/mlas/lib/power/FgemmKernelpower.h:155:27: error: use of undeclared identifier 'vec_splat'
	ABroadcast[Row] = vec_splat(AElements[Row], Lane);