devel/sabre: fix build with jdk21
The patch for build.xml hardcoded java 5 source and target which is not available for javac in openjdk21. I removed the source and target.

[javac] Compiling 80 source files to /wrkdirs/usr/ports/devel/sabre/work/Simple API for Binary REpresentations (SABRE)/build/classes
[javac] warning: [options] bootstrap class path not set in conjunction with -source 5
[javac] error: Source option 5 is no longer supported. Use 8 or later.
[javac] error: Target option 5 is no longer supported. Use 8 or later.

Later JDKs are more picky about the charset used. Also for characters in comments. I hinted the encoding for the compiler.

[javac] /wrkdirs/usr/ports/devel/sabre/work/Simple API for Binary REpresentations (SABRE)/src/java/de/tu_darmstadt/informatik/rbg/bstickler/udflib/tools/OSTAIdentifierTranslation.java:6: error: unmappable character (0xF6) for encoding UTF-8
[javac]  *	Bj?rn Stickler <...>

PR:	291571