databases/sabiql: Update to 1.8.2
- Add a patch to fix compilation that fails with error:

   Compiling sabiql v1.8.2 (/usr/local/poudriere/ports/default/databases/sabiql/work/sabiql-1.8.2)
     Running `CARGO=/usr/local/bin/cargo CARGO_CRATE_NAME=sabiql CARGO_MANIFEST_DIR=/usr/local/poudriere/ports/default/databases/sabiql/work/sabiql-1.8.2 CARGO_MANIFEST_PATH=/usr/local/
poudriere/ports/default/databases/sabiql/work/sabiql-1.8.2/Cargo.toml CARGO_PKG_AUTHORS='' CARGO_PKG_DESCRIPTION='A fast, driver-less TUI for browsing and editing PostgreSQL databases'
CARGO_PKG_HOMEPAGE='https://github.com/riii111/sabiql' CARGO_PKG_LICENSE=MIT CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=sabiql CARGO_PKG_README=README.md CARGO_PKG_REPOSITORY='https://git
hub.com/riii111/sabiql' CARGO_PKG_RUST_VERSION='' CARGO_PKG_VERSION=1.8.2 CARGO_PKG_VERSION_MAJOR=1 CARGO_PKG_VERSION_MINOR=8 CARGO_PKG_VERSION_PATCH=2 CARGO_PKG_VERSION_PRE='' CARGO_PR
IMARY_PACKAGE=1 CARGO_SBOM_PATH='' LD_LIBRARY_PATH=/usr/local/poudriere/ports/default/databases/sabiql/work/target/release/deps /usr/local/bin/rustc --crate-name sabiql --edition=2024 s
rc/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=185 --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C panic=abo
rt -C linker-plugin-lto -C codegen-units=1 --cfg 'feature="default"' --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values("default", "self-update", "test-support"))' -C metad
ata=023aa7efa197a4c3 -C extra-filename=-c3302537da996148 --out-dir /usr/local/poudriere/ports/default/databases/sabiql/work/target/release/deps -C strip=debuginfo -L dependency=/usr/loc
al/poudriere/ports/default/databases/sabiql/work/target/release/deps --extern arboard=/usr/local/poudriere/ports/default/databases/sabiql/work/target/release/deps/libarboard-b05642fb4bb
bf497.rmeta --extern async_trait=/usr/local/poudriere/ports/default/databases/sabiql/work/target/release/deps/libasync_trait-0b30c34429310070.so --extern clap=/usr/local/poudriere/ports
/default/databases/sabiql/work/target/release/deps/libclap-73f3e9c8259edfeb.rmeta --extern color_eyre=/usr/local/poudriere/ports/default/databases/sabiql/work/target/release/deps/libcol
or_eyre-fb47ae523ef2a63d.rmeta --extern crossterm=/usr/local/poudriere/ports/default/databases/sabiql/work/target/release/deps/libcrossterm-83bbf2edf76e9a5c.rmeta --extern csv=/usr/loca
l/poudriere/ports/default/databases/sabiql/work/target/release/deps/libcsv-3023b491e6c320f3.rmeta --extern dirs=/usr/local/poudriere/ports/default/databases/sabiql/work/target/release/d
eps/libdirs-e1d501ab877ee9ac.rmeta --extern dotenvy=/usr/local/poudriere/ports/default/databases/sabiql/work/target/release/deps/libdotenvy-d0fc367384634408.rmeta --extern futures=/usr/
local/poudriere/ports/default/databases/sabiql/work/target/release/deps/libfutures-b1d7fd39e74026c6.rmeta --extern lru=/usr/local/poudriere/ports/default/databases/sabiql/work/target/re
lease/deps/liblru-d7e03bbf2187fe6b.rmeta --extern nucleo_matcher=/usr/local/poudriere/ports/default/databases/sabiql/work/target/release/deps/libnucleo_matcher-00618533db104ed6.rmeta --
extern ratatui=/usr/local/poudriere/ports/default/databases/sabiql/work/target/release/deps/libratatui-7c776fcd22192fd7.rmeta --extern regex=/usr/local/poudriere/ports/default/databases
/sabiql/work/target/release/deps/libregex-38ab5a0769c02199.rmeta --extern serde=/usr/local/poudriere/ports/default/databases/sabiql/work/target/release/deps/libserde-809190d238f75c25.rm
eta --extern serde_json=/usr/local/poudriere/ports/default/databases/sabiql/work/target/release/deps/libserde_json-1382b0fd2b7b7340.rmeta --extern tokio=/usr/local/poudriere/ports/defau
lt/databases/sabiql/work/target/release/deps/libtokio-3f93b4377f9c8feb.rmeta --extern tokio_util=/usr/local/poudriere/ports/default/databases/sabiql/work/target/release/deps/libtokio_ut
il-6490ea11331ef749.rmeta --extern toml=/usr/local/poudriere/ports/default/databases/sabiql/work/target/release/deps/libtoml-4e8be3396d805d34.rmeta --extern urlencoding=/usr/local/poudr
iere/ports/default/databases/sabiql/work/target/release/deps/liburlencoding-d2acc5cece62d9bc.rmeta --extern uuid=/usr/local/poudriere/ports/default/databases/sabiql/work/target/release/
deps/libuuid-11409636b0ebcfa4.rmeta -C linker=cc`
error: FolderOpener: unsupported target OS
  --> src/infra/adapters/folder_opener.rs:16:9
   |
16 |         compile_error!("FolderOpener: unsupported target OS");
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

ChangeLog:

  - https://github.com/riii111/sabiql/releases/tag/v1.8.0
  - https://github.com/riii111/sabiql/releases/tag/v1.8.1
  - https://github.com/riii111/sabiql/releases/tag/v1.8.2

Reported by:	riii111 <notifications@github.com>