net/ecal: mark BROKEN due to asio incompat
The upstream release 6.0.0 might fix these,
but might also incur other issues.

evidence from a poudriere 14.2-RELEASE amd64 jail:

[00:00:40] /usr/local/libexec/ccache/c++ -DASIO_DISABLE_VISIBILITY -DASIO_STANDALONE -D_WIN32_WINNT=0x0601 -Dtcp_pubsub_EXPORTS -I/wrkdirs/usr/ports/net/ecal/work/ecal-5.13.3/thirdparty/tcp_pubsub/tcp_pubsub/tcp_pubsub/include -I/wrkdirs/usr/ports/net/ecal/work/.build/thirdparty/tcp_pubsub/tcp_pubsub/tcp_pubsub/include -I/wrkdirs/usr/ports/net/ecal/work/ecal-5.13.3/thirdparty/tcp_pubsub/tcp_pubsub/tcp_pubsub/src -I/wrkdirs/usr/ports/net/ecal/work/ecal-5.13.3/thirdparty/asio/asio/asio/include -I/wrkdirs/usr/ports/net/ecal/work/ecal-5.13.3/thirdparty/recycle/recycle/src -O2 -pipe  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing   -pthread -isystem /usr/local/include -std=c++17 -O2 -pipe  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing   -pthread -isystem /usr/local/include -std=c++17  -DNDEBUG -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -Wall -Wextra -Wall -Wextra -pthread -MD -MT thirdparty/tcp_pubsub/tcp_pubsub/tcp_pubsub/CMakeFiles/tcp_pubsub.dir/src/publisher_session.cpp.o -MF thirdparty/tcp_pubsub/tcp_pubsub/tcp_pubsub/CMakeFiles/tcp_pubsub.dir/src/publisher_session.cpp.o.d -o thirdparty/tcp_pubsub/tcp_pubsub/tcp_pubsub/CMakeFiles/tcp_pubsub.dir/src/publisher_session.cpp.o -c /wrkdirs/usr/ports/net/ecal/work/ecal-5.13.3/thirdparty/tcp_pubsub/tcp_pubsub/tcp_pubsub/src/publisher_session.cpp
[00:00:40] In file included from /wrkdirs/usr/ports/net/ecal/work/ecal-5.13.3/thirdparty/tcp_pubsub/tcp_pubsub/tcp_pubsub/src/publisher_session.cpp:4:
[00:00:40] /wrkdirs/usr/ports/net/ecal/work/ecal-5.13.3/thirdparty/tcp_pubsub/tcp_pubsub/tcp_pubsub/src/publisher_session.h:40:50: error: no member named 'io_service' in namespace 'asio'
[00:00:40]    40 |     PublisherSession(const std::shared_ptr<asio::io_service>&                               io_service
[00:00:40]       |                                            ~~~~~~^
[00:00:40] /wrkdirs/usr/ports/net/ecal/work/ecal-5.13.3/thirdparty/tcp_pubsub/tcp_pubsub/tcp_pubsub/src/publisher_session.h:101:27: error: no member named 'io_service' in namespace 'asio'
[00:00:40]   101 |     std::shared_ptr<asio::io_service> io_service_;
[00:00:40]       |                     ~~~~~~^
[00:00:40] /wrkdirs/usr/ports/net/ecal/work/ecal-5.13.3/thirdparty/tcp_pubsub/tcp_pubsub/tcp_pubsub/src/publisher_session.h:113:11: error: no member named 'io_service' in namespace 'asio'
[00:00:40]   113 |     asio::io_service::strand  data_strand_;
[00:00:40]       |     ~~~~~~^
[00:00:40] /wrkdirs/usr/ports/net/ecal/work/ecal-5.13.3/thirdparty/tcp_pubsub/tcp_pubsub/tcp_pubsub/src/publisher_session.cpp:32:66: error: no member named 'io_service' in namespace 'asio'
[00:00:40]    32 |   PublisherSession::PublisherSession(const std::shared_ptr<asio::io_service>&                               io_service
[00:00:40]       |                                                            ~~~~~~^
[00:00:40] /wrkdirs/usr/ports/net/ecal/work/ecal-5.13.3/thirdparty/tcp_pubsub/tcp_pubsub/tcp_pubsub/src/publisher_session.cpp:109:29: error: no matching member function for call to 'shared_from_this'
[00:00:40]   109 |     session_closed_handler_(shared_from_this()); // Run the completion handler
[00:00:40]       |                             ^~~~~~~~~~~~~~~~
[...]
[00:00:40] fatal error: too many errors emitted, stopping now [-ferror-limit=]
[00:00:40] 20 errors generated.