security/py-certbot: added missing runtime dep py-typing-extensions
Fixes error message:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 5, in <module>
    from certbot.main import main
  File "/usr/local/lib/python3.11/site-packages/certbot/main.py", line 6, in <module>
    from certbot._internal import main as internal_main
  File "/usr/local/lib/python3.11/site-packages/certbot/_internal/main.py", line 20, in <module>
    import josepy as jose
  File "/usr/local/lib/python3.11/site-packages/josepy/__init__.py", line 41, in <module>
    from josepy.json_util import (
  File "/usr/local/lib/python3.11/site-packages/josepy/json_util.py", line 25, in <module>
    from OpenSSL import crypto
  File "/usr/local/lib/python3.11/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/usr/local/lib/python3.11/site-packages/OpenSSL/SSL.py", line 42, in <module>
    from OpenSSL.crypto import (
  File "/usr/local/lib/python3.11/site-packages/OpenSSL/crypto.py", line 26, in <module>
    from typing_extensions import deprecated
ModuleNotFoundError: No module named 'typing_extensions'

PR:		286283
Reported by:	dweimer@dweimer.net