graphics/py-fotokilof: Update to 5.1.7
- Fix app/name in the new file pyproject.toml to match PORTNAME,
 otherwise the build fails with the error:

===>   Generating temporary packing list
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/site-packages/installer/__main__.py", line 98, in <module>
    _main(sys.argv[1:], "python -m installer")
  File "/usr/local/lib/python3.11/site-packages/installer/__main__.py", line 86, in _main
    with WheelFile.open(args.wheel) as source:
  File "/usr/local/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/installer/sources.py", line 162, in open
    with zipfile.ZipFile(path) as f:
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/zipfile.py", line 1295, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: /usr/local/poudriere/ports/default/graphics/py-fotokilof/work-py311/FotoKilof-5.1.7/dist/fotokilof-5.1.7*.whl
*** Error code 1

Release changes:	https://github.com/TeaM-TL/FotoKilof/releases/tag/5.1.7
Reported by:	Tomasz Łuczak <notifications@github.com>