games/veloren-weekly: unbreak build after 53274b1a3736
error[E0277]: expected a `FnMut(&mut veloren_common::comp::ControlAction)` closure, found `RangeFull`
    --> common/systems/src/mount.rs:74:49
     |
74   | ...                   .extract_if(.., |action| match action {
     |                        ---------- ^^ expected an `FnMut(&mut veloren_common::comp::ControlAction)` closure, found `RangeFull`
     |                        |
     |                        required by a bound introduced by this call
     |
     = help: the trait `for<'a> FnMut(&'a mut veloren_common::comp::ControlAction)` is not implemented for `RangeFull`
note: required by a bound in `Vec::<T, A>::extract_if`
    --> /usr/local/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:3236:12
     |
3234 |     pub fn extract_if<F>(&mut self, filter: F) -> ExtractIf<'_, T, F, A>
     |            ---------- required by a bound in this associated function
3235 |     where
3236 |         F: FnMut(&mut T) -> bool,
     |            ^^^^^^^^^^^^^^^^^^^^^ required by this bound in `Vec::<T, A>::extract_if`

error[E0277]: expected a `FnMut(&mut veloren_common::comp::ControlAction)` closure, found `RangeFull`
  --> common/systems/src/mount.rs:74:38
   |
74 | ...                   .extract_if(.., |action| match action {
   |                        ^^^^^^^^^^ expected an `FnMut(&mut veloren_common::comp::ControlAction)` closure, found `RangeFull`
   |
   = help: the trait `for<'a> FnMut(&'a mut veloren_common::comp::ControlAction)` is not implemented for `RangeFull`
note: required by a bound in `std::vec::ExtractIf`
  --> /usr/local/lib/rustlib/src/rust/library/alloc/src/vec/extract_if.rs:28:8
   |
22 | pub struct ExtractIf<
   |            --------- required by a bound in this struct
...
28 |     F: FnMut(&mut T) -> bool,
   |        ^^^^^^^^^^^^^^^^^^^^^ required by this bound in `ExtractIf`

error[E0061]: this method takes 1 argument but 2 arguments were supplied
    --> common/systems/src/mount.rs:74:38
     |
74   |   ...                   .extract_if(.., |action| match action {
     |  ________________________^^^^^^^^^^_____-
75   | | ...                       ControlAction::StartInput { input: i, .. }
76   | | ...                       | ControlAction::CancelInput(i) => matches!(
77   | | ...                           i,
...    |
80   | | ...                       _ => false,
81   | | ...                   })
     | |_______________________- unexpected argument #2 of type `{closure@common/systems/src/mount.rs:74:53: 74:61}`
     |
note: method defined here
    --> /usr/local/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:3234:12
     |
3234 |     pub fn extract_if<F>(&mut self, filter: F) -> ExtractIf<'_, T, F, A>
     |            ^^^^^^^^^^
help: remove the extra argument
     |
74   -                                     .extract_if(.., |action| match action {
75   -                                         ControlAction::StartInput { input: i, .. }
76   -                                         | ControlAction::CancelInput(i) => matches!(
77   -                                             i,
78   -                                             InputKind::Jump | InputKind::Fly | InputKind::Roll
79   -                                         ),
80   -                                         _ => false,
81   -                                     })
74   +                                     .extract_if(..)
     |

error[E0599]: the method `collect` exists for struct `ExtractIf<'_, ControlAction, RangeFull>`, but its trait bounds were not satisfied
  --> common/systems/src/mount.rs:82:38
   |
72 |   ...                   let actions = c
   |  _____________________________________-
73 | | ...                       .actions
74 | | ...                       .extract_if(.., |action| match action {
75 | | ...                           ControlAction::StartInput { input: i, .. }
...  |
81 | | ...                       })
82 | | ...                       .collect();
   | |                           -^^^^^^^ method cannot be called on `ExtractIf<'_, ControlAction, RangeFull>` due to unsatisfied trait bounds
   | |___________________________|
   |
   |
  ::: /usr/local/lib/rustlib/src/rust/library/core/src/ops/range.rs:43:1
   |
43 |   pub struct RangeFull;
   |   -------------------- doesn't satisfy `<_ as FnOnce<(&mut ControlAction,)>>::Output = bool` or `_: FnMut<(&mut ControlAction,)>`
   |
  ::: /usr/local/lib/rustlib/src/rust/library/alloc/src/vec/extract_if.rs:22:1
   |
22 | / pub struct ExtractIf<
23 | |     'a,
24 | |     T,
25 | |     F,
26 | |     #[unstable(feature = "allocator_api", issue = "32838")] A: Allocator = Global,
27 | | > where
   | |_- doesn't satisfy `_: Iterator`
   |
   = note: the following trait bounds were not satisfied:
           `<RangeFull as FnOnce<(&mut veloren_common::comp::ControlAction,)>>::Output = bool`
           which is required by `std::vec::ExtractIf<'_, veloren_common::comp::ControlAction, RangeFull>: Iterator`
           `RangeFull: FnMut<(&mut veloren_common::comp::ControlAction,)>`
           which is required by `std::vec::ExtractIf<'_, veloren_common::comp::ControlAction, RangeFull>: Iterator`
           `std::vec::ExtractIf<'_, veloren_common::comp::ControlAction, RangeFull>: Iterator`
           which is required by `&mut std::vec::ExtractIf<'_, veloren_common::comp::ControlAction, RangeFull>: Iterator`

error[E0277]: expected a `FnMut(&mut veloren_common::comp::ControlAction)` closure, found `RangeFull`
    --> common/systems/src/mount.rs:183:33
     |
183  |                     .extract_if(.., |action| match action {
     |                      ---------- ^^ expected an `FnMut(&mut veloren_common::comp::ControlAction)` closure, found `RangeFull`
     |                      |
     |                      required by a bound introduced by this call
     |
     = help: the trait `for<'a> FnMut(&'a mut veloren_common::comp::ControlAction)` is not implemented for `RangeFull`
note: required by a bound in `Vec::<T, A>::extract_if`
    --> /usr/local/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:3236:12
     |
3234 |     pub fn extract_if<F>(&mut self, filter: F) -> ExtractIf<'_, T, F, A>
     |            ---------- required by a bound in this associated function
3235 |     where
3236 |         F: FnMut(&mut T) -> bool,
     |            ^^^^^^^^^^^^^^^^^^^^^ required by this bound in `Vec::<T, A>::extract_if`

error[E0277]: expected a `FnMut(&mut veloren_common::comp::ControlAction)` closure, found `RangeFull`
   --> common/systems/src/mount.rs:183:22
    |
183 |                     .extract_if(.., |action| match action {
    |                      ^^^^^^^^^^ expected an `FnMut(&mut veloren_common::comp::ControlAction)` closure, found `RangeFull`
    |
    = help: the trait `for<'a> FnMut(&'a mut veloren_common::comp::ControlAction)` is not implemented for `RangeFull`
note: required by a bound in `std::vec::ExtractIf`
   --> /usr/local/lib/rustlib/src/rust/library/alloc/src/vec/extract_if.rs:28:8
    |
22  | pub struct ExtractIf<
    |            --------- required by a bound in this struct
...
28  |     F: FnMut(&mut T) -> bool,
    |        ^^^^^^^^^^^^^^^^^^^^^ required by this bound in `ExtractIf`

error[E0061]: this method takes 1 argument but 2 arguments were supplied
    --> common/systems/src/mount.rs:183:22
     |
183  |                       .extract_if(.., |action| match action {
     |  ______________________^^^^^^^^^^_____-
184  | |                         ControlAction::StartInput { input: i, .. }
185  | |                         | ControlAction::CancelInput(i) => {
186  | |                             matches!(i, InputKind::Jump | InputKind::Fly | InputKind::Roll)
187  | |                         },
188  | |                         _ => false,
189  | |                     })
     | |_____________________- unexpected argument #2 of type `{closure@common/systems/src/mount.rs:183:37: 183:45}`
     |
note: method defined here
    --> /usr/local/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:3234:12
     |
3234 |     pub fn extract_if<F>(&mut self, filter: F) -> ExtractIf<'_, T, F, A>
     |            ^^^^^^^^^^
help: remove the extra argument
     |
183  -                     .extract_if(.., |action| match action {
184  -                         ControlAction::StartInput { input: i, .. }
185  -                         | ControlAction::CancelInput(i) => {
186  -                             matches!(i, InputKind::Jump | InputKind::Fly | InputKind::Roll)
187  -                         },
188  -                         _ => false,
189  -                     })
183  +                     .extract_if(..)
     |

error[E0599]: the method `collect` exists for struct `ExtractIf<'_, ControlAction, RangeFull>`, but its trait bounds were not satisfied
   --> common/systems/src/mount.rs:190:22
    |
181 |                   let actions: Vec<_> = c
    |  _______________________________________-
182 | |                     .actions
183 | |                     .extract_if(.., |action| match action {
184 | |                         ControlAction::StartInput { input: i, .. }
...   |
189 | |                     })
190 | |                     .collect();
    | |                     -^^^^^^^ method cannot be called on `ExtractIf<'_, ControlAction, RangeFull>` due to unsatisfied trait bounds
    | |_____________________|
    |
    |
   ::: /usr/local/lib/rustlib/src/rust/library/core/src/ops/range.rs:43:1
    |
43  |   pub struct RangeFull;
    |   -------------------- doesn't satisfy `<_ as FnOnce<(&mut ControlAction,)>>::Output = bool` or `_: FnMut<(&mut ControlAction,)>`
    |
   ::: /usr/local/lib/rustlib/src/rust/library/alloc/src/vec/extract_if.rs:22:1
    |
22  | / pub struct ExtractIf<
23  | |     'a,
24  | |     T,
25  | |     F,
26  | |     #[unstable(feature = "allocator_api", issue = "32838")] A: Allocator = Global,
27  | | > where
    | |_- doesn't satisfy `_: Iterator`
    |
    = note: the following trait bounds were not satisfied:
            `<RangeFull as FnOnce<(&mut veloren_common::comp::ControlAction,)>>::Output = bool`
            which is required by `std::vec::ExtractIf<'_, veloren_common::comp::ControlAction, RangeFull>: Iterator`
            `RangeFull: FnMut<(&mut veloren_common::comp::ControlAction,)>`
            which is required by `std::vec::ExtractIf<'_, veloren_common::comp::ControlAction, RangeFull>: Iterator`
            `std::vec::ExtractIf<'_, veloren_common::comp::ControlAction, RangeFull>: Iterator`
            which is required by `&mut std::vec::ExtractIf<'_, veloren_common::comp::ControlAction, RangeFull>: Iterator`

Some errors have detailed explanations: E0061, E0277, E0599.
For more information about an error, try `rustc --explain E0061`.
error: could not compile `veloren-common-systems` (lib) due to 8 previous errors