www/py-django-photologue: Fix stage QA
* This was overlooked in 21900d66eda3 and was then noticed
  retrospectively during a bulk run after stage QA was extended in
  f35f902eb8f1:

[...]
====> Running Q/A tests (stage-qa)
Error: Python package installs top-level 'scripts/' directory in site-packages
Error:   Location: lib/python3.11/site-packages/scripts
[...]

* Bump PORTREVISION due changed package contents.

Approved by:	portmgr (build fix blanket)
Fixes:	21900d66eda3 www/py-django-photologue: Update to 3.18