x11/swww: Update to 0.10.3
- Update list of build dependencies
- Use the variable CARGO_INSTALL_PATH to fix the build that otherwise fails
  with the error:

===>   Generating temporary packing list
error: found a virtual manifest at `/usr/local/poudriere/ports/default/x11/swww/work/swww-0.10.3/Cargo.toml` instead of a package manifest
*** Error code 101

- Add pkg-message (shown when upgrading from a version lesser than 0.10)

Release changes:	https://github.com/LGFae/swww/releases/tag/v0.10.3
Reported by:	Leonardo Gibrowski Faé <notifications@github.com>