devel/py-virtualenv: Update to 20.35.3
- Mark as broken the test tests/unit/create/via_global_ref/test_build_c_ext.py
  that fails with the following error:

  ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
  ERROR: No matching distribution found for setuptools>=40.8.0

Release changes:	https://github.com/pypa/virtualenv/releases/tag/20.35.3
Reported by:	Bernát Gábor <notifications@github.com>