math/openblas: fix build on powerpc64
-lm is necessary:
/usr/local/bin/ld: ../libopenblas_ppc970p-r0.3.33.a(bgemm_thread_nn.o): undefined reference to symbol 'sqrt@@FBSD_1.0'
/usr/local/bin/ld: /lib/libm.so.5: error adding symbols: DSO missing from command line