graphics/openexr: fix build on Sandy Bridge CPUs
OpenEXR attempts to use F16C intrinsics when AVX available and
at least one of these is true: F16C available, GCC used, or clang used.

Intel Sandy Bridge processors do have AVX extensions,
but no F16C instruction set extension, so compilers (clang 19, 20, gcc 14)
complain:

work/openexr-3.4.4/src/lib/OpenEXRCore/unpack.c:37:18:
  error: always_inline function '_mm256_cvtph_ps' requires target feature 'f16c',
  but would be inlined into function 'half_to_float_buffer'
  that is compiled without support for 'f16c'
   37 |             out, _mm256_cvtph_ps (_mm_loadu_si128 ((const __m128i*) in)));
      |                  ^

Not bumping PORTREVISION because this is not a supported configuration.

https://github.com/AcademySoftwareFoundation/openexr/issues/2231

Reported by:	"UnitedMarsupials"
MFH:		2025Q4